#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# contents of commit message in file at $1
commitMessage="$(cat $1)"
#echo "message: $commitMessage"

# rebuild _site
npm run build

# copy build at _site to _dist
cp -r ./_site/* ./_dist

# enter gh-pages branch
cd _dist

# stage all files
git add -A

# commit all files with commit message from main
git commit -m "$commitMessage"

# push to github
git push origin gh-pages